# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SimpleTxtTranslator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleTxtTranslator

  target 'SimpleTxtTranslatorTests' do
    inherit! :search_paths
    pod 'SwiftyJSON'
    # Pods for testing
  end

end
