//
//  Languages.swift
//  SimpleTxtTranslator
//
//  Created by camila oliveira on 08/05/18.
//  Copyright © 2018 Aliamcami. All rights reserved.
//

import UIKit

public enum Languages: String {
    case Automatic = "auto"
    case Afrikaans = "af"
    case Albanian = "sq"
    case Amharic = "am"
    case Arabic = "ar"
    case Armenian = "hy"
    case Azerbaijani = "az"
    case Basque = "eu"
    case Belarusian = "be"
    case Bengali = "bn"
    case Bosnian = "bs"
    case Bulgarian = "bg"
    case Catalan = "ca"
    case Cebuano = "ceb"
    case Chichewa = "ny"
    case Chinese_Simplified = "zh-cn"
    case Chinese_Traditional = "zh-tw"
    case Corsican = "co"
    case Croatian = "hr"
    case Czech = "cs"
    case Danish = "da"
    case Dutch = "nl"
    case English = "en"
    case Esperanto = "eo"
    case Estonian = "et"
    case Filipino = "tl"
    case Finnish = "fi"
    case French = "fr"
    case Frisian = "fy"
    case Galician = "gl"
    case Georgian = "ka"
    case German = "de"
    case Greek = "el"
    case Gujarati = "gu"
    case Haitian_Creole = "ht"
    case Hausa = "ha"
    case Hawaiian = "haw"
    case Hebrew = "iw"
    case Hindi = "hi"
    case Hmong = "hmn"
    case Hungarian = "hu"
    case Icelandic = "is"
    case Igbo = "ig"
    case Indonesian = "id"
    case Irish = "ga"
    case Italian = "it"
    case Japanese = "ja"
    case Javanese = "jw"
    case Kannada = "kn"
    case Kazakh = "kk"
    case Khmer = "km"
    case Korean = "ko"
    case Kurdish_Kurmanji = "ku"
    case Kyrgyz = "ky"
    case Lao = "lo"
    case Latin = "la"
    case Latvian = "lv"
    case Lithuanian = "lt"
    case Luxembourgish = "lb"
    case Macedonian = "mk"
    case Malagasy = "mg"
    case Malay = "ms"
    case Malayalam = "ml"
    case Maltese = "mt"
    case Maori = "mi"
    case Marathi = "mr"
    case Mongolian = "mn"
    case Myanmar_Burmese = "my"
    case Nepali = "ne"
    case Norwegian = "no"
    case Pashto = "ps"
    case Persian = "fa"
    case Polish = "pl"
    case Portuguese = "pt"
    case Punjabi = "ma"
    case Romanian = "ro"
    case Russian = "ru"
    case Samoan = "sm"
    case Scots_Gaelic = "gd"
    case Serbian = "sr"
    case Sesotho = "st"
    case Shona = "sn"
    case Sindhi = "sd"
    case Sinhala = "si"
    case Slovak = "sk"
    case Slovenian = "sl"
    case Somali = "so"
    case Spanish = "es"
    case Sundanese = "su"
    case Swahili = "sw"
    case Swedish = "sv"
    case Tajik = "tg"
    case Tamil = "ta"
    case Telugu = "te"
    case Thai = "th"
    case Turkish = "tr"
    case Ukrainian = "uk"
    case Urdu = "ur"
    case Uzbek = "uz"
    case Vietnamese = "vi"
    case Welsh = "cy"
    case Xhosa = "xh"
    case Yiddish = "yi"
    case Yoruba = "yo"
    case Zulu = "zu"
}

